development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://kziyngoipduolx:d3ba13ec142dcb3761aee9399615d80bdef22d01c9a591437d1fc898199b11dd@ec2-174-129-218-106.compute-1.amazonaws.com:5432/d6algtgrvdlsaj
  channel_prefix: first_app_production
